<<<<<<< HEAD
spring.application.name=ai-debugger-service
server.port=8083

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/ai_debugger
spring.datasource.username=shree
spring.datasource.password=

# Ollama
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.model.embedding=ollama
spring.ai.ollama.embedding.model=nomic-embed-text

# PGVector
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
=======
spring.application.name=order-service
>>>>>>> 350717006f66235f68133eb16a1f77c83d14c991
